In [2]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(12,)

In [6]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a[2]

array([ 8,  9, 10, 11])

In [9]:
a[2,1]

9

In [10]:
a[:,1]

array([1, 5, 9])

In [12]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])